# Generated by Django 4.0.4 on 2022-04-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftdetail',
            name='mint',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
